apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels: 
    name: pv01
spec:
  nfs:
    path: /data/volumes/volume1
    server: 172.16.107.104
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
  labels: 
    name: pv02
spec:
  nfs:
    path: /data/volumes/volume2
    server: 172.16.107.104
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
  labels: 
    name: pv03
spec:
  nfs:
    path: /data/volumes/volume3
    server: 172.16.107.104
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv04
  labels: 
    name: pv04
spec:
  nfs:
    path: /data/volumes/volume4
    server: 172.16.107.104
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv05
  labels: 
    name: pv05
spec:
  nfs:
    path: /data/volumes/volume5
    server: 172.16.107.104
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
    storage: 2Gi
